# Generated by Django 4.2.8 on 2024-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
