# Generated by Django 4.2.8 on 2024-01-07 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_model', '0002_alter_car_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_model.car_model')),
            ],
        ),
    ]
