# Generated by Django 4.2.8 on 2024-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
